### ISSUE TITLE
Assertion error in TestGitOperations

### ISSUE THREAD

**Issue by ilai-deutel** [PawelLipski/git-machete#1331] opened 2024-09-18 03:07 UTC
Hello,

`test_is_equivalent_tree_or_patch_reachable` is failing when I run the test suite locally on master:

```bash
$ python -m pytest -p tests.pytest_full_operands --numprocesses=auto --junitxml=test-results/testenv-py.xml -m 'not completion_e2e'
==================================================================== test session starts =====================================================================
platform linux -- Python 3.12.6, pytest-8.3.2, pluggy-1.5.0
cachedir: .tox/py/.pytest_cache
rootdir: git-machete
configfile: tox.ini
plugins: mock-3.14.0, xdist-3.6.1, clarity-1.0.1
4 workers [293 items]   
.......................................................F.............................................................................................. [ 51%]
...............................................................................................................................................        [100%]
========================================================================== FAILURES ==========================================================================
___________________________ TestGitOperations.test_is_equivalent_tree_or_patch_reachable_with_squash_merge_and_commits_in_between ____________________________
[gw3] linux -- Python 3.12.6 git-machete/.tox/py/bin/python

self = <tests.test_git_operations.TestGitOperations object at 0x7e629237be30>

    def test_is_equivalent_tree_or_patch_reachable_with_squash_merge_and_commits_in_between(self) -> None:
        (
            self.repo_sandbox.new_branch("master")
                .commit("master first commit")
                .new_branch("feature")
                .commit("feature commit")
                .check_out("master")
                .commit("extra commit")
        )
    
        git = GitContext()
        assert git._run_git("merge", "--squash", "feature", flush_caches=False) == 0
        assert git._run_git("commit", "-m", "squashed", flush_caches=False) == 0
    
        feature = AnyRevision("feature")
        master = AnyRevision("master")
    
        # Here the simple method will not detect the squash merge, as there are commits in master before we merged feature so
        # there's no tree hash in master that matches the tree hash of feature
        assert git.is_equivalent_tree_reachable(equivalent_to=feature, reachable_from=master) is False
        assert git.is_equivalent_patch_reachable(equivalent_to=feature, reachable_from=master) is True
    
        self.repo_sandbox.check_out("master").commit("another master commit")
        git.flush_caches()  # so that the old position of `master` isn't remembered
    
        assert git.is_equivalent_tree_reachable(equivalent_to=feature, reachable_from=master) is False
>       assert git.is_equivalent_patch_reachable(equivalent_to=feature, reachable_from=master) is True
E       AssertionError: assert False is True
E        +  where False = is_equivalent_patch_reachable(equivalent_to='feature', reachable_from='master')
E        +    where is_equivalent_patch_reachable = <git_machete.git_operations.GitContext object at 0x7e62921af230>.is_equivalent_patch_reachable

git-machete/tests/test_git_operations.py:96: AssertionError
-------------------------------------------------------------------- Captured stdout call --------------------------------------------------------------------
[master (root-commit) 9939088] master first commit
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 0.txt
[feature 3a6d3fc] feature commit
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 1.txt
[master 6d612f6] extra commit
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 2.txt
Squash commit -- not updating HEAD
[master af257b6] squashed
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 1.txt
[master 0bb9e7c] another master commit
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 3.txt
-------------------------------------------------------------------- Captured stderr call --------------------------------------------------------------------
Switched to a new branch 'master'
Switched to a new branch 'feature'
Switched to branch 'master'
Automatic merge went well; stopped before committing as requested
Already on 'master'
================================================================== short test summary info ===================================================================
FAILED tests/test_git_operations.py::TestGitOperations::test_is_equivalent_tree_or_patch_reachable_with_squash_merge_and_commits_in_between - AssertionError: assert False is True
```

I am using git version 2.46.1

**Comment by PawelLipski** [comment] 2024-09-18 13:07
Yeah, I've noticed this issue a couple days ago as well... this is caused by an unfortunate update in git 2.46.1 (2.46.0 is not yet affected), specifically the parser in `git patch-id` (https://github.com/VirtusLab/git-machete/issues/1329). I [posted this issue to git@vger.kernel.org](https://lore.kernel.org/git/CAB+6q+Ks1BVE-PAP0sKDKzjMZ4=Lfcv7LfwGrB9GToRTn24oww@mail.gmail.com/T/#u), so far with no reply ☹️ I'll introduce a workaround for specific git versions instead

**Comment by PawelLipski** [comment] 2024-09-18 14:23
Worked around in #1333

**Comment by PawelLipski** [comment] 2024-09-18 15:34
Btw I've also added a check for whether `makepkg` passes on PR https://github.com/VirtusLab/git-machete/pull/1326 to avoid surprises down the road when building [package for AUR](https://aur.archlinux.org/packages/git-machete). Thanks for updating to 3.29.2, I was about to flag 😅 

Once v3.29.3 with the fix for this issue is out (later today), could you apply the following update to PKGBUILD (as I don't seem to have permissions to modify this file):

```diff
--- a/PKGBUILD
+++ b/PKGBUILD
@@ -12,7 +12,7 @@ makedepends=(python-build python-installer python-wheel python-setuptools)
 optdepends=('bash: bash completion'
             'fish: fish completion'
             'zsh: zsh completion')
-checkdepends=('python-pytest' 'python-pytest-mock')
+checkdepends=('python-pytest' 'python-pytest-mock' 'python-pytest-xdist')
 source=("${pkgname}-${pkgver}.tar.gz::https://github.com/VirtusLab/$pkgname/archive/v$pkgver.tar.gz")
 sha256sums=('9b94cbfc762fe9d5b7ebf4747a83b4eebae2b351e9442a0274f41c233fbf0103')

@@ -29,8 +29,7 @@ build() {

 check() {
   cd "$srcdir/$pkgname-${pkgver}"
-  # https://github.com/VirtusLab/git-machete/issues/1331
-  GITHUB_TOKEN='' pytest  -m 'not completion_e2e' -k 'not test_is_equivalent_tree_or_patch_reachable_with_squash_merge_and_commits_in_between'
+  pytest --numprocesses=auto -m 'not completion_e2e' -vv
 }

 package() {
```

`python-xdist` and `--numprocesses=auto` just for faster execution. `GITHUB_TOKEN=''` shouldn't be necessary anymore (and if it is, then mocks are missing somewhere in the tests, which needs to be fixed). `-vv` for easier debug in case of build failure in the future.

Btw, is there actually any way to view the build logs of this AUR package?

**Closed as completed** 2024-09-18 17:51 UTC
Labels: bug, underlying git

**Comment by ilai-deutel** [comment] 2024-09-19 00:48
> `GITHUB_TOKEN=''` shouldn't be necessary anymore (and if it is, then mocks are missing somewhere in the tests, which needs to be fixed). 

Tests fail if I call ` export GITHUB_TOKEN=abc`:

```
FAILED tests/test_github.py::TestGitHub::test_github_get_token_from_gh - AssertionError: assert GitHubToken(value='abc', provider='`GITHUB_TOKEN` environment variable') is None
FAILED tests/test_github.py::TestGitHub::test_github_get_token_from_hub - AssertionError: assert GitHubToken(value='abc', provider='`GITHUB_TOKEN` environment variable') is None
ERROR tests/test_github.py::TestGitHub::test_github_token_retrieval_order - Exception: Patched methods have never been called: os.path.isfile, shutil.which
ERROR tests/test_github.py::TestGitHub::test_github_get_token_from_file_in_home_directory - Exception: Patched methods have never been called: os.path.isfile, builtins.open
ERROR tests/test_github.py::TestGitHub::test_github_get_token_from_gh - Exception: Patched methods have never been called: os.path.isfile, shutil.which, git_machete.utils._popen_cmd
ERROR tests/test_github.py::TestGitHub::test_github_get_token_from_hub - Exception: Patched methods have never been called: git_machete.utils._popen_cmd, os.path.isfile, shutil.which, builtins.open
```

> could you apply the following update to PKGBUILD

Updated

> Btw, is there actually any way to view the build logs of this AUR package?

AUR packages are not built centrally, users are expected to use the `PKGBUILD` to build the package from source (using `makepkg`) so there are no server-side build logs. I can share the build logs on my machine if there is anything in particular you want to see.

**Comment by PawelLipski** [comment] 2024-09-19 09:18
> Tests fail if I call  export GITHUB_TOKEN=abc:

Whoops good spot, fixed at https://github.com/VirtusLab/git-machete/pull/1338. I haven't noticed as I always run the tests via `tox`, which doesn't pass env vars from outside to the invoked processes.

**Comment by PawelLipski** [comment] 2024-10-10 09:26
@ilai-deutel 3.30.0 is released, `GITHUB_TOKEN=` can be removed from https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=git-machete#n32
